name: AI Naming Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AI Naming Reviewer
        run: |
          npm install -g ai-naming-reviewer

      - name: Run Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BLACKBOX_API_KEY: ${{ secrets.BLACKBOX_API_KEY }}
        run: ai-naming-review
