name: AI Naming Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: AI Naming Review
        uses: BidaultArmand/blackbox42@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          blackbox-api-key: ${{ secrets.BLACKBOX_API_KEY }}
          mode: review
